name: Linter Check

on: push

jobs:
  lint:
    name: Linter Check
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Installing packages
        run: bun

      - name: Prettier/ESLint Check
        run: bun run lint
